[package]
label = "users"
version = "0.1.3"

[package.sets]
atom = "https://github.com/ekala-project/atom"
home = ["::", "https://github.com/nrdxp/home"]

[compose.with.atom-nix]
from = "atom"
entry = "nrd"

[deps.from.home]
nix = "^0.1.0"
term = "^0.1.0"
wm = "^0.1.0"
